version: '3.2'

services:
  foo_db:
    hostname: foo_db
    container_name: foo_db
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ../../docker_data/db:/var/lib/mysql #storing db data (requires empty directory ../../docker_data/db)
      - ../../docker_data/dump:/tmp #share db dump directory for manual import from container console
    environment:
      MYSQL_ROOT_PASSWORD: 'rootpwd'

  foo_php:
    hostname: foo_php
    container_name: foo_php
    build:
      context: ./
      dockerfile: php.Dockerfile
    links:
      - foo_db
    volumes:
      - ../../www:/var/www
      - ../../docker_data/tmp:/tmp

  foo_web:
    hostname: foo_web
    container_name: foo_web
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./hosts:/etc/nginx/conf.d
      - ../../www:/var/www
      - ../../docker_data/logs/nginx:/var/log/nginx
    links:
      - foo_php
    extra_hosts:
      - "foo.local:127.0.0.1"

  foo_pma:
    hostname: foo_pma
    container_name: foo_pma
    image: phpmyadmin
    #    restart: always
    ports:
      - 81:80
    extra_hosts:
      - "foo.pma:127.0.0.1"
    links:
      - foo_db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=foo_db
      - PMA_USER=root
      - PMA_PASSWORD=rootpwd
